 const data = {
    industry: [
        {
            title: "actors and extras",
            img: "Extras2_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Comedy actors" },
                { title: "entertainers" },
                { title: "event actors" },
                { title: "feature film actors" },
                { title: "music videos" },
                { title: "presenters" },
                { title: " film actors" },
                { title: " theatre actors" },
                { title: " commercial actors" },
                { title: " tv series actors" },
                { title: " voiceover actors" },
                { title: " web actors" },
                { title: " others " },
            ]
        },
        {
            title: "dancers",
            img: "Dancers_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: " Acro dance " },
                { title: " Ballet " },
                { title: " Ballroom dance " },
                { title: " Baroque dance " },
                { title: " B-boying " },
                { title: " Belly dance " },
                { title: " Cha-cha-cha " },
                { title: " Chicago stepping " },
                { title: " Choreographers " },
                { title: " Circle dance " },
                { title: " Contemporary dance " },
                { title: " Country-western dance " },
                { title: " Dance Movement Psychotherapist " },
                { title: " Dance Teachers " },
                { title: " Disco " },
                { title: " Erotic dancing " },
                { title: " Fandango " },
                { title: " Flamenco " },
                { title: " Folk dance " },
                { title: " Hip-hop dance " },
                { title: " Jazz dance " },
                { title: " Jive " },
                { title: " Krumping " },
                { title: " Lambada " },
                { title: " Lap dance " },
                { title: " others " },
                { title: " Limbo " },
                { title: " Line dance " },
                { title: " Live Performance " },
                { title: " Mambo " },
                { title: " Modern dance " },
                { title: " Pole dance " },
                { title: " Polka " },
                { title: " Quickstep " },
                { title: " Salsa " },
                { title: " Sequence dance " },
                { title: " Street dance " },
                { title: " Swing " },
                { title: " Tango " },
                { title: " Tap dance " },
                { title: " Twist " },
                { title: " Two-step " },
                { title: " Waltz " },
                { title: " War dance " },
                { title: " Zumba " },
                { title: " Lavani Dancers " },
                { title: " Kathak Dancers " },
                { title: " others " },
            ]
        },
        {
            title: "musicians",
            img: "Artist_Managers_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Banjo Players" },
                { title: "Bass Guitarists" },
                { title: "Bassoonists" },
                { title: "Cellists" },
                { title: "Clarinetists" },
                { title: "Composers" },
                { title: "Double Bassists" },
                { title: "DJ" },
                { title: "Drummers" },
                { title: "Engineer" },
                { title: "Flautists" },
                { title: "Guitarists" },
                { title: "Harpists" },
                { title: "Horn Players" },
                { title: "Music therapist" },
                { title: "Ovoists" },
                { title: "Percussionists" },
                { title: "Pianists" },
                { title: "Producers" },
                { title: "Rapper" },
                { title: "Saxophonists" },
                { title: "Singers" },
                { title: "Teachers" },
                { title: "Trombonists" },
                { title: "Trumpeters" },
                { title: "Tubists" },
                { title: "Violinists" },
                { title: "Violists" },
                { title: "Sitarist" },
                { title: "Sarod Player" },
                { title: "Tabla Player" },
                { title: "others" },
            ]
        },
        {
            title: "models",
            img: "Actors_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Alternative models" },
                { title: "Art models" },
                { title: "Atmosphere models" },
                { title: "Commercial print and on-camera models" },
                { title: "Event Models" },
                { title: "Fashion models" },
                { title: "Fitness models" },
                { title: "Glamour models" },
                { title: "Hair Models" },
                { title: "Parts models" },
                { title: "Plus-size models" },
                { title: "Presenters" },
                { title: "Promotional models" },
                { title: "Spokesmodels" },
                { title: "Supermodels" },
                { title: "TFP / TFCD Models" },
                { title: "Trade show models" },
                { title: "TV Commercial models" },
                { title: "TV Models" },
                { title: "others" },
            ]
        },
        // {
        //     title: "art and craft",
        //     img: "art2.jpg",
        //     categories: [
        //         { title: "Craft" },
        //         { title: "Mat Designing" },
        //         { title: "Paper Craft" },
        //         { title: "feature film actors" },
        //         { title: "Handicraft" },
        //         { title: "Bangle Makers" },
        //         { title: "Beadwork" },
        //         { title: "Balloon Modelling" },
        //         { title: "Banner-Making" },
        //         { title: "Calligraphy" },
        //         { title: "Cross-Stitch" },
        //         { title: "Crocheting" },
        //         { title: "Felting" },
        //         { title: "Knitting" },
        //         { title: "Lace-making" },
        //         { title: "Macrame" },
        //         { title: "Millinery" },
        //         { title: "Needlepoint" },
        //         { title: "Patchwork" },
        //         { title: "Quilting" },
        //         { title: "Rug Making" },
        //         { title: "Sewing" },
        //         { title: "Shoemaking" },
        //         { title: "String Art" },
        //         { title: "Tapestry" },
        //         { title: "Weaving" },
        //         { title: "T-shirt art" },
        //         { title: "Metalworking" },
        //         { title: "Jewelry" },
        //         { title: "Pottery" },
        //         { title: "Sculpture" },
        //         { title: "Woodworking" },
        //         { title: "Cabinet making" },
        //         { title: "Marquetry" },
        //         { title: "Lacquerware" },
        //         { title: "Wood Burning" },
        //         { title: "Wood Turning" },
        //         { title: "Bookbinding" },
        //         { title: "Cardmaking" },
        //         { title: "Collage" },
        //         { title: "Card Modelling" },
        //         { title: "Decoupage" },
        //         { title: "Embossing" },
        //         { title: "Iris Folding" },
        //         { title: "Marbling" },
        //         { title: "Origami" },
        //         { title: "Papercraft" },
        //         { title: "Papier-Mache" },
        //         { title: "Parchment craft" },
        //         { title: "Quilling or Paper Filigree" },
        //         { title: "Scrapbooking" },
        //         { title: "Stamping (with a rubber stamp)" },
        //         { title: "Basket weaving" },
        //         { title: "Corn Dolly Making" },
        //         { title: "Floral Design" },
        //         { title: "Pressed Flower Craft" },
        //         { title: "Straw Marquetry" },
        //         { title: "Doll Making" },
        //         { title: "Dollhouse construction and furnishing" },
        //         { title: "Egg Decorating" },
        //         { title: "Etching" },
        //         { title: "Glassblowing" },
        //         { title: "Lapidary" },
        //         { title: "Mosaics" },
        //         { title: "Stained Glass" },
        //         { title: "Toy Making" },
        //         { title: "Polymer Clay" },
        //         { title: "Nerikomi Pottery" },
        //         { title: "Thermocol Artist" },
        //         { title: "Mosaics" },
        //         { title: "Mosaics" },

        //     ]
        // },

        // {
        //     title: "art collector",
        //     img: "a6.jpg",
        //     categories: [
        //         { title: " others " }
        //     ]
        // },
        // {
        //     title: "art consultant",
        //     img: "a5.jpg",
        //     categories: [
        //         { title: " others " }
        //     ]
        // },
        // {
        //     title: "art dealer",
        //     img: "art5.jpg",
        //     categories: [
        //         { title: " others " }
        //     ]
        // },
        // {
        //     title: "art seller",
        //     img: "v5.jpg",
        //     categories: [
        //         { title: " others " }
        //     ]
        // },
        {
            title: "artist manager",
            img: "Artist_Managers2_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Technical Manager" },
                { title: "Tour Manager" },
                { title: "Road Manager" },
                { title: "Production Manager" },
                { title: "Event Manager" },
                { title: "Business Manager" },
                { title: "others" },
            ]
        },
        // {
        //     title: "body artist",
        //     img: "v7.jpg",
        //     categories: [
        //         { title: "Scarification" },
        //         { title: "Subdermal Implant" },
        //         { title: "Scalpelling" },
        //         { title: "Heena/ Mehndi" },
        //         { title: "Body Piercing" },
        //         { title: "others" },
        //     ]
        // },
        {
            title: "circus artist",
            img: "Circus_Artists2_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Tumblers" },
                { title: "Entertainers" },
                { title: "Contortionist" },
                { title: "Aerialists" },
                { title: "Acrobats" },
                { title: "Rola Bola Artist" },
                { title: "Fire Performer" },
                { title: "Tumbling Artist" },
                { title: "Pole Art" },
                { title: "Acro-Balancer" },
                { title: "Hand Balancer" },
                { title: "Stilt Walker" },
                { title: "Whip Cracker" },
                { title: "Juggler" },
                { title: "Cyr Wheel" },
                { title: "Contortionist" },
                { title: "Unicycler" },
                { title: "Tight Rope Walker" },
                { title: "Hula Hoop Artist" },
                { title: "others" }
            ]
        },
        // {
        //     title: "clairvoyant",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Palmistry" },
        //         { title: "Astrologer" },
        //         { title: "Numerologist" },
        //         { title: "Horoscopist" },
        //         { title: "Tarot Cards Reader" },
        //         { title: "Naturopathy" },
        //         { title: "Vaastu Shastra" },
        //         { title: "others" }
        //     ]
        // },
        {
            title: "comedians",
            img: "Comedians2_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Alternative comedy" },
                { title: "Black comedy or dark comedy" },
                { title: "Blue comedy" },
                { title: "Character comedy" },
                { title: "Cringe comedy" },
                { title: "Deadpan comedy" },
                { title: "Improvisational Comedians" },
                { title: "Improvisational comedy" },
                { title: "Insult Comedy" },
                { title: "Mockumentary" },
                { title: "Musical Comedy" },
                { title: "Observational comedy" },
                { title: "Physical comedy" },
                { title: "Prop Comedians" },
                { title: "Prop comedy" },
                { title: "Sitcom" },
                { title: "Sketch" },
                { title: "Solo Stand-Ups" },
                { title: "Spoof" },
                { title: "Surreal comedy" },
                { title: "Topical comedy/Satire" },
                { title: "Troupe Comedians" },
                { title: "Wit/Word play" },
                { title: "Mimicry Artist" },
                { title: "others" }
            ]
        },
        // {
        //     title: "culinary artist",
        //     img: "6.jpg",
        //     categories: [
        //         { title: " others " }
        //     ]
        // },

        {
            title: "designers",
            img: "Designers2_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: " Digital Art " },
                { title: " Graphic Design " },
                { title: " Industrial Design " },
                { title: " Fashion Design " },
                { title: " Decorative Arts " },
                { title: " Graphic Arts " },
                { title: " Video Editor " },
                { title: " Block Printing " },
                { title: " Game Programmer " },
                { title: " 3D Environment Artist  " },
                { title: " 3D Character Modeller " },
                { title: " VFX Artist  " },
                { title: " VFX Compositor " },
                { title: " Game Developer " },
                { title: " Animator " },
                { title: " others " },
            ]
        },
        // {
        //     title: "drama",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Applied Drama" },
        //         { title: "Augustan drama" },
        //         { title: "Christian drama" },
        //         { title: "Closet drama" },
        //         { title: "Costume drama" },
        //         { title: "Creative Drama" },
        //         { title: "Crime drama" },
        //         { title: "Domestic drama" },
        //         { title: "Drama film" },
        //         { title: "Dramatherapist" },
        //         { title: "Dramatic structure" },
        //         { title: "Dramatic theory" },
        //         { title: "Dramaturgy" },
        //         { title: "Entertainment" },
        //         { title: "Flash drama" },
        //         { title: "Folk play" },
        //         { title: "Heroic drama" },
        //         { title: "History of theatre" },
        //         { title: "Hyperdrama" },
        //         { title: "Legal drama" },
        //         { title: "Medical drama" },
        //         { title: "Melodrama" },
        //         { title: "Monodrama" },
        //         { title: "Mystery play" },
        //         { title: "One act play" },
        //         { title: "Opera" },
        //         { title: "Pantomime" },
        //         { title: "Play" },
        //         { title: "Political drama" },
        //         { title: "Radio drama" },
        //         { title: "Soap opera" },
        //         { title: "Theatre" },
        //         { title: "Theatre Artist" },
        //         { title: "Theatre awards" },
        //         { title: "Theatre Director" },
        //         { title: "Theatre Manager" },
        //         { title: "Theatre Stage Manager" },
        //         { title: "Two-hander" },
        //         { title: "Verse drama and dramatic verse" },
        //         { title: "Well-made play" },
        //         { title: "Yakshagana-An Indian musical drama" },
        //         { title: "others" },
        //     ]
        // },
        {
            title: "film and stage crew",
            img: "Film_and_Stage_Crew_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Animation" },
                { title: "Art Department" },
                { title: "Camera" },
                { title: "Camera & lighting" },
                { title: "Casting" },
                { title: "Competition & Festivals" },
                { title: "Costume" },
                { title: "Costume department" },
                { title: "Director" },
                { title: "Editing" },
                { title: "Electrical" },
                { title: "Grips" },
                { title: "Hair and make-up" },
                { title: "Lighting" },
                { title: "Post-production" },
                { title: "Production" },
                { title: "Sound Production" },
                { title: "Sound & Music" },
                { title: "Special effects" },
                { title: "Stunts" },
                { title: "Others" },
                { title: "VFX" },
                { title: "Documentary Films" },
                { title: "Short Films" },
                { title: "Feature Films" },
                { title: "Print Coordinator" },
                { title: "Film Print Collector and Dispatcher" },
                { title: "Film Programmer" },
                { title: "Cinematographer" },
                { title: "Sound Designer" },
                { title: "Production Designer" },
                { title: "Electronic Cinematographer" },
                { title: "TV Engineer" },
                { title: "Production Coordinator" },
                { title: "Production Manager" },
                { title: "Line Producer" },
                { title: "VFX Line Producer" },
                { title: "others" },
            ]
        },
        {
            title: "makeup artist",
            img: "Film_and_Stage_Crew2_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Beauty" },
                { title: "Body and Face Painting" },
                { title: "Fashion" },
                { title: "Film and Movies" },
                { title: "Personal Services" },
                { title: "Television" },
                { title: "Theatrical" },
                { title: "Special Make-Up Effects (FX Makeup)" },
                { title: "Airbrushing" },
                { title: "Bridal" },
                { title: "High Definition" },
                { title: "Wigs" },
                { title: "others" },
            ]
        },
        // {
        //     title: "healing artist",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Acupuncture" },
        //         { title: "Masseuse" },
        //         { title: "Crystal Healing" },
        //         { title: "Quantum Healing" },
        //         { title: "Reiki" },
        //         { title: "Soul Healing" },
        //         { title: "Angel Healing" },
        //         { title: "others" },
        //     ]
        // },
        // {
        //     title: "host and anchors",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Television Presenter" },
        //         { title: "News Presenter" },
        //         { title: "Weather Presenter" },
        //         { title: "Radio Presenter" },
        //         { title: "Sports Presenter" },
        //         { title: "Emcee" },
        //         { title: "others" },
        //     ]
        // },
        {
            title: "magician and illustrationist",
            img: "Magicians_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Bizarre magic" },
                { title: "Children's magic" },
                { title: "Comedy Magic" },
                { title: "Corporate magic / Trade show magic" },
                { title: "Escapology" },
                { title: "Gospel magic" },
                { title: "Mathemagic" },
                { title: "Mentalism" },
                { title: "Micromagic / Close-up magic / Table magic" },
                { title: "Online magic tricks" },
                { title: "Parlor magic" },
                { title: "Pickpocket magicians" },
                { title: "Platform magic  / Cabaret magic / Stand-up magic" },
                { title: "Quick Change Magic" },
                { title: "Shock magic" },
                { title: "Stage illusions" },
                { title: "Street magic" },
                { title: "Theatrical s?ances" },
                { title: "others" },
            ]
        },
        {
            title: "media and journalism",
            img: "Journalists2_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Broadcast Journalism" },
                { title: "Multimedia Journalism" },
                { title: "Print Journalism" },
                { title: "Photo Journalism" },
                { title: "Online Journalism" },
                { title: "others" },
            ]
        },


        // {
        //     title: "other artist",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Event Organizers" },
        //         { title: "Film Production House" },
        //         { title: "Others" },
        //         { title: "Publication House" },
        //         { title: "Corporate Organisations" },
        //         { title: "Magazines & Newspapers" },
        //         { title: "others" },
        //     ]
        // },
        {
            title: "painters and sketchers",
            img: "art5.jpg",
            categories: [
                { title: "Acrylic" },
                { title: "Enamel" },
                { title: "Fresco" },
                { title: "Gouache" },
                { title: "Hot wax" },
                { title: "Ink" },
                { title: "Oil" },
                { title: "Pastel" },
                { title: "Spray Paint" },
                { title: "Tempera" },
                { title: "Water Miscible Oil Paint" },
                { title: "Watercolor" },
                { title: "Charcoal" },
                { title: "Graphite" },
                { title: "Pastel" },
                { title: "Pencil" },
                { title: "Silverpoint" },
                { title: "2D Paint Artist " },
                { title: "others" },
            ]
        },
        // {
        //     title: "photographers",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Fictional photographers" },
        //         { title: "Landscape Photographer" },
        //         { title: "Macro Photographer" },
        //         { title: "Time Lapse Photographer" },
        //         { title: "Travel Photographer" },
        //         { title: "Event Photography" },
        //         { title: "Wedding Photography" },
        //         { title: "Commercial Photography" },
        //         { title: "Studio Photography" },
        //         { title: "Documentary Photography" },
        //         { title: "Photojournalism" },
        //         { title: "Portraits" },
        //         { title: "Editorial Photography" },
        //         { title: "Candid Photography" },
        //         { title: "Fine Art Photography" },
        //         { title: "others" },
        //     ]
        // },
        {
            title: "sculphurist",
            img: "art3.jpg",
            categories: [
                { title: "Ceramics" },
                { title: "Digital Art" },
                { title: "Fiber Art" },
                { title: "Glass" },
                { title: "Jewelry" },
                { title: "Metal" },
                { title: "Mixed Media" },
                { title: "Pottery" },
                { title: "Printmaking" },
                { title: "Stone" },
                { title: "Wood" },
                { title: "Lego Artist" },
                { title: "others" },
            ]
        },
        // {
        //     title: "stunt artist",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Fire Performer" },
        //         { title: "Stunt Coordinator" },
        //         { title: "Motorcycle stunts" },
        //         { title: "Rope Stunt" },
        //         { title: "Martial Arts" },
        //         { title: "Boxing" },
        //         { title: "Trampolining" },
        //         { title: "High Diving" },
        //         { title: "Horse Riding" },
        //         { title: "Car Stunts" },
        //         { title: "Gymnastic" },
        //         { title: "Rock climbing" },
        //         { title: "Sub Aqua" },
        //         { title: "Freestyle Sportbike Riding" },
        //         { title: "others" },
        //     ]
        // },
        // {
        //     title: "tatoo artist",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Traditional" },
        //         { title: "Realism" },
        //         { title: "Watercolour" },
        //         { title: "Tribal" },
        //         { title: "Neo Traditional " },
        //         { title: "Japanese" },
        //         { title: "Dotwork" },
        //         { title: "Script" },
        //         { title: "Portraiture" },
        //         { title: "others" },
        //     ]
        // },
        // {
        //     title: "tourism",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Adventure Tourism" },
        //         { title: "Business Tourism" },
        //         { title: "Culinary Tourism" },
        //         { title: "Cultural Tourism" },
        //         { title: "Doom Tourism" },
        //         { title: "Ecotourism" },
        //         { title: "Genealogy Tourism" },
        //         { title: "LGBT Tourism" },
        //         { title: "Medical Tourism" },
        //         { title: "Nautical Tourism" },
        //         { title: "Religious Tourism" },
        //         { title: "Space Tourism" },
        //         { title: "others" },
        //     ]
        // },
        // {
        //     title: "video production",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Videographer" },
        //         { title: "Cinematographer" },
        //         { title: "Video Editor" },
        //         { title: "others" },
        //     ]
        // },
        // {
        //     title: "voice over artist and radio jockey",
        //     img: "6.jpg",
        //     categories: [
        //         { title: "Dubbing Artist" },
        //         { title: "Radio Broadcasting" },
        //         { title: "Radio Host" },
        //         { title: "Emcee" },
        //         { title: "Storyteller" },
        //         { title: "others" },
        //     ]
        // },
        {
            title: "writers and poet",
            img: "Journalists_1x1_1080x1080_Instagram_Optimized.jpg",
            categories: [
                { title: "Bhajan" },
                { title: "Comedy" },
                { title: "Couplets: Doha" },
                { title: "Devotional" },
                { title: "Drama" },
                { title: "Epic" },
                { title: "Fiction" },
                { title: "Folk poetry" },
                { title: "Ghazal" },
                { title: "Non-fiction" },
                { title: "Realistic fiction" },
                { title: "Romance novel" },
                { title: "Satire" },
                { title: "Tragedy" },
                { title: "Tragicomedy" },
                { title: "Script Writers" },
                { title: "Screen Writers" },
                { title: "others" },
            ]
        }
    ]
}

export default data